### ISSUE TITLE
Weight Lag

### ISSUE THREAD

**Issue by ThomasCNotts** [leifeld/tnam#1]
Why is there no pathdist parameter on the weightlag term?

**Comment by leifeld** [comment]
That's because of the way the `weightlag` is computed. It's done by matrix multiplication. Also, it's unclear how you would choose the threshold value for counting something as a connection. E.g., in the network of international trade, there are basically ties between all nodes in the network, indicating the different trade volumes. The path distance between any sender country and any receiver country is 1 because all countries are directly connected by some (at least minimal) trade flows. A solution could be to weight the strength of connection, but then you would need to conflate two different things: the weight and the decay. That said, if node A is connected to everybody through some trade amount, then that means that the `weightlag` term should incorporate everybody else's (weighted) influence on A through the multiplication. So I wouldn't worry about this. It's like in spatial regression where you are not just taking into account adjacent regions but all other regions as well, weighted by their distance to the focal region.

**Comment by leifeld** [comment]
Please re-open if there are any follow-up questions.
