### ISSUE TITLE
Using a network as an independent variable

### ISSUE THREAD

**Issue by ThomasCNotts** [leifeld/tnam#3]
I have data that essentially looks like this:
Network, Seed size, Diffusion
i.e. a set of different networks and some data that goes along with each.

I'd like to run a regression, something like this:
Diffusion ~ Seed size + Clustering + Average path length + Number of components...

But instead can I use tnam to run a regression using the weighted network structure itself as an independent variable rather than extracting summary variables from the network data? Like this:
Diffusion ~ Seed size + Network

**Comment by leifeld** [comment]
Correct me if I misunderstood this: you are interested in the variation between networks (e.g., in terms of the number of adopters), rather than in the variation between nodes nested in a single network (i.e., on some nodal attribute). If that sounds about right, then TNAM is not for you. TNAM models the diffusion within a network at the level of nodes, possibly over time.

**Comment by ThomasCNotts** [comment]
Yes that's right and thank you for the information.



Sent from my tablet - please excuse any typos.


-------- Original message --------

**Comment by leifeld** [comment]
I think you could just use a GLM framework in this case, e.g., a Poisson regression for count data, to model the number of adopters per network as a function of network-level characteristics. The reason is that the networks are independent from each other, which means the i.i.d. assumption is not violated. Good luck!
